# Use a full Python image instead of slim for more comprehensive build tools
FROM python:3.9

# Set environment variables for Flask
ENV FLASK_APP=app.py
ENV FLASK_RUN_HOST=0.0.0.0
ENV FLASK_RUN_PORT=5000

# Set the working directory in the container
WORKDIR /app

# Copy the dependencies file to the working directory
COPY jira_pptx_app/requirements.txt .

# Install any needed packages specified in requirements.txt with verbose output
RUN pip install --no-cache-dir -vvv -r requirements.txt

# Copy all other source code to the working directory
COPY jira_pptx_app/ .

# Expose the port the app runs on
EXPOSE 5000

# Run the Flask application
CMD ["flask", "run"]
